select 
pat.APPRAISAL_TEMPLATE_ID
,pat.NAME
,pat.DATE_FROM
,pat.DATE_TO
,pat.ASSESSMENT_TYPE_ID
,pat.RATING_SCALE_ID
,pat.QUESTIONNAIRE_TEMPLATE_ID
,pat.FINAL_SCORE_FORMULA_ID
,passt.ASSESSMENT_TYPE_ID
,passt.NAME
,passt.DATE_TO
,passt.DATE_FROM
,passt.RATING_SCALE_ID
,passt.WEIGHTING_SCALE_ID
,pa.APPRAISAL_ID
,pa.APPRAISAL_TEMPLATE_ID
,pa.APPRAISEE_PERSON_ID
,pa.APPRAISER_PERSON_ID
,pa.GROUP_INITIATOR_ID
,pa.APPRAISAL_PERIOD_END_DATE
,pa.APPRAISAL_PERIOD_START_DATE
,pa.STATUS
,pa.OVERALL_PERFORMANCE_LEVEL_ID
,pa.ATTRIBUTE_CATEGORY
,pa.MAIN_APPRAISER_ID
,pa.EVENT_ID
,pa.PLAN_ID
,passe.ASSESSMENT_ID
,passe.PERSON_ID
,passe.ASSESSMENT_TYPE_ID
,passe.ASSESSOR_PERSON_ID
,passe.ASSESSMENT_GROUP_ID
,passe.ASSESSMENT_PERIOD_START_DATE
,passe.ASSESSMENT_PERIOD_END_DATE
,passe.TOTAL_SCORE
,passe.APPRAISAL_ID
,passe.ATTRIBUTE_CATEGORY
,ppmp.PLAN_ID
,ppmp.PLAN_NAME
,ppmp.ADMINISTRATOR_PERSON_ID
,ppmp.PREVIOUS_PLAN_ID
,ppmp.START_DATE
,ppmp.END_DATE
,ppmp.SUPERVISOR_ID
,ppmp.SUPERVISOR_ASSIGNMENT_ID
,ppmp.ATTRIBUTE_CATEGORY
,pcd.COMPETENCE_DEFINITION_ID
,pcd.SEGMENT1
,pcd.START_DATE_ACTIVE
,pcd.END_DATE_ACTIVE
,pc.COMPETENCE_ID
,pc.NAME
,pc.DATE_FROM
,pc.DATE_TO
,pc.BEHAVIOURAL_INDICATOR
,pc.MIN_LEVEL
,pc.MAX_LEVEL
,pc.RATING_SCALE_ID
,pc.ATTRIBUTE_CATEGORY
,pce.COMPETENCE_ELEMENT_ID
,pce.COMPETENCE_ID
,pce.PROFICIENCY_LEVEL_ID
,pce.PARENT_COMPETENCE_ELEMENT_ID
,pce.ASSESSMENT_ID
,pce.ASSESSMENT_TYPE_ID
,pce.EFFECTIVE_DATE_FROM
,pce.EFFECTIVE_DATE_TO
,pce.COMPETENCE_TYPE
from
per_appraisal_templates pat join per_assessment_types passt on pat.ASSESSMENT_TYPE_ID=passt.ASSESSMENT_TYPE_ID
join per_appraisals pa on pa.APPRAISAL_TEMPLATE_ID=pat.APPRAISAL_TEMPLATE_ID
join per_assessments passe on passt.ASSESSMENT_TYPE_ID=passe.ASSESSMENT_TYPE_ID and pa.APPRAISAL_ID=passe.APPRAISAL_ID
join per_perf_mgmt_plans ppmp on ppmp.PLAN_ID=pa.PLAN_ID
join per_competence_elements pce on pce.ASSESSMENT_ID=passe.ASSESSMENT_ID
join per_competences pc on pce.COMPETENCE_ID=pc.COMPETENCE_ID
join per_competence_definitions pcd on pcd.COMPETENCE_DEFINITION_ID=pc.COMPETENCE_DEFINITION_ID







